--
-- Atomic CRM schema for a standalone Postgres (Railway).
-- Ported from supabase/schemas/, with all Supabase-specific pieces removed:
-- no auth.users (replaced by public.users), no RLS/policies, no storage schema,
-- and no triggers (sales_id defaulting, avatar/favicon enrichment, last_seen
-- updates, attachment cleanup and user<->sales sync are done in the API layer).
--

create extension if not exists "citext";

-- Authentication table (replaces Supabase auth.users).
create table if not exists public.users (
    id uuid primary key default gen_random_uuid(),
    email citext not null unique,
    encrypted_password text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table if not exists public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamptz,
    last_seen timestamptz,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table if not exists public.contact_notes (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    text text,
    date timestamptz default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table if not exists public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    archived_at timestamptz,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table if not exists public.deal_notes (
    id bigint generated by default as identity primary key,
    deal_id bigint not null,
    type text,
    text text,
    date timestamptz default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table if not exists public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index if not exists uq__sales__user_id on public.sales using btree (user_id);

create table if not exists public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamptz,
    done_date timestamptz,
    sales_id bigint
);

create table if not exists public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table if not exists public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--
alter table public.companies
    drop constraint if exists companies_sales_id_fkey,
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    drop constraint if exists contacts_company_id_fkey,
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    drop constraint if exists contacts_sales_id_fkey,
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    drop constraint if exists contact_notes_contact_id_fkey,
    add constraint contact_notes_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    drop constraint if exists contact_notes_sales_id_fkey,
    add constraint contact_notes_sales_id_fkey foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    drop constraint if exists deals_company_id_fkey,
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    drop constraint if exists deals_sales_id_fkey,
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    drop constraint if exists deal_notes_deal_id_fkey,
    add constraint deal_notes_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    drop constraint if exists deal_notes_sales_id_fkey,
    add constraint deal_notes_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.sales
    drop constraint if exists sales_user_id_fkey,
    add constraint sales_user_id_fkey foreign key (user_id) references public.users(id) on delete cascade;

alter table public.tasks
    drop constraint if exists tasks_contact_id_fkey,
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

--
-- Indexes on foreign keys
--
create index if not exists contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index if not exists contacts_company_id_idx on public.contacts using btree (company_id);
create index if not exists deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index if not exists deals_company_id_idx on public.deals using btree (company_id);

--
-- Views
--
create or replace view public.activity_log as
select
    ('company.' || c.id || '.created') as id,
    'company.created' as type,
    c.created_at as date,
    c.id as company_id,
    c.sales_id,
    to_json(c.*) as company,
    null::json as contact,
    null::json as deal,
    null::json as contact_note,
    null::json as deal_note
from public.companies c
union all
select
    ('contact.' || co.id || '.created') as id,
    'contact.created' as type,
    co.first_seen as date,
    co.company_id,
    co.sales_id,
    null::json as company,
    to_json(co.*) as contact,
    null::json as deal,
    null::json as contact_note,
    null::json as deal_note
from public.contacts co
union all
select
    ('contactNote.' || cn.id || '.created') as id,
    'contactNote.created' as type,
    cn.date,
    co.company_id,
    cn.sales_id,
    null::json as company,
    null::json as contact,
    null::json as deal,
    to_json(cn.*) as contact_note,
    null::json as deal_note
from public.contact_notes cn
    left join public.contacts co on co.id = cn.contact_id
union all
select
    ('deal.' || d.id || '.created') as id,
    'deal.created' as type,
    d.created_at as date,
    d.company_id,
    d.sales_id,
    null::json as company,
    null::json as contact,
    to_json(d.*) as deal,
    null::json as contact_note,
    null::json as deal_note
from public.deals d
union all
select
    ('dealNote.' || dn.id || '.created') as id,
    'dealNote.created' as type,
    dn.date,
    d.company_id,
    dn.sales_id,
    null::json as company,
    null::json as contact,
    null::json as deal,
    null::json as contact_note,
    to_json(dn.*) as deal_note
from public.deal_notes dn
    left join public.deals d on d.id = dn.deal_id;

create or replace view public.companies_summary as
select
    c.id,
    c.created_at,
    c.name,
    c.sector,
    c.size,
    c.linkedin_url,
    c.website,
    c.phone_number,
    c.address,
    c.zipcode,
    c.city,
    c.state_abbr,
    c.sales_id,
    c.context_links,
    c.country,
    c.description,
    c.revenue,
    c.tax_identifier,
    c.logo,
    count(distinct d.id) as nb_deals,
    count(distinct co.id) as nb_contacts
from public.companies c
    left join public.deals d on c.id = d.company_id
    left join public.contacts co on c.id = co.company_id
group by c.id;

create or replace view public.contacts_summary as
select
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.email_jsonb,
    co.phone_jsonb,
    (jsonb_path_query_array(co.email_jsonb, '$[*]."email"'))::text as email_fts,
    (jsonb_path_query_array(co.phone_jsonb, '$[*]."number"'))::text as phone_fts,
    c.name as company_name,
    count(distinct t.id) filter (where t.done_date is null) as nb_tasks
from public.contacts co
    left join public.tasks t on co.id = t.contact_id
    left join public.companies c on co.company_id = c.id
group by co.id, c.name;

--
-- Seed the singleton configuration row so updateConfiguration always has a target.
--
insert into public.configuration (id, config) values (1, '{}'::jsonb)
on conflict (id) do nothing;
