--
-- Multi-tenancy (pooled model): every data row is tagged with organization_id,
-- and the API scopes every query to the caller's organization. Existing data is
-- migrated into a single default organization (id = 1).
--

create table if not exists public.organizations (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamptz not null default now(),
    config jsonb not null default '{}'::jsonb
);

-- Default organization for pre-existing data.
insert into public.organizations (id, name)
select 1, 'Default Organization'
where not exists (select 1 from public.organizations where id = 1);

-- Keep the identity sequence ahead of any explicit id we inserted.
select setval(
    pg_get_serial_sequence('public.organizations', 'id'),
    greatest(coalesce((select max(id) from public.organizations), 1), 1)
);

-- Add organization_id to every tenant-scoped table (nullable, then backfilled).
alter table public.companies add column if not exists organization_id bigint;
alter table public.contacts add column if not exists organization_id bigint;
alter table public.deals add column if not exists organization_id bigint;
alter table public.contact_notes add column if not exists organization_id bigint;
alter table public.deal_notes add column if not exists organization_id bigint;
alter table public.tasks add column if not exists organization_id bigint;
alter table public.tags add column if not exists organization_id bigint;
alter table public.sales add column if not exists organization_id bigint;

update public.companies set organization_id = 1 where organization_id is null;
update public.contacts set organization_id = 1 where organization_id is null;
update public.deals set organization_id = 1 where organization_id is null;
update public.contact_notes set organization_id = 1 where organization_id is null;
update public.deal_notes set organization_id = 1 where organization_id is null;
update public.tasks set organization_id = 1 where organization_id is null;
update public.tags set organization_id = 1 where organization_id is null;
update public.sales set organization_id = 1 where organization_id is null;

do $$
declare
    t text;
begin
    foreach t in array array[
        'companies', 'contacts', 'deals', 'contact_notes',
        'deal_notes', 'tasks', 'tags', 'sales'
    ]
    loop
        execute format('alter table public.%I alter column organization_id set not null', t);
        execute format('alter table public.%I drop constraint if exists %I', t, t || '_organization_id_fkey');
        execute format(
            'alter table public.%I add constraint %I foreign key (organization_id) references public.organizations(id) on delete cascade',
            t, t || '_organization_id_fkey'
        );
        execute format('create index if not exists %I on public.%I (organization_id)', t || '_organization_id_idx', t);
    end loop;
end $$;

-- Move the singleton configuration into the default org, then retire the table.
update public.organizations o
set config = c.config
from public.configuration c
where o.id = 1 and c.id = 1;

drop table if exists public.configuration;

--
-- Recreate the summary/activity views with organization_id so reads can scope.
--
drop view if exists public.activity_log;
drop view if exists public.companies_summary;
drop view if exists public.contacts_summary;

create view public.companies_summary as
select
    c.id,
    c.created_at,
    c.name,
    c.sector,
    c.size,
    c.linkedin_url,
    c.website,
    c.phone_number,
    c.address,
    c.zipcode,
    c.city,
    c.state_abbr,
    c.sales_id,
    c.context_links,
    c.country,
    c.description,
    c.revenue,
    c.tax_identifier,
    c.logo,
    c.organization_id,
    count(distinct d.id) as nb_deals,
    count(distinct co.id) as nb_contacts
from public.companies c
    left join public.deals d on c.id = d.company_id
    left join public.contacts co on c.id = co.company_id
group by c.id;

create view public.contacts_summary as
select
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.email_jsonb,
    co.phone_jsonb,
    co.organization_id,
    (jsonb_path_query_array(co.email_jsonb, '$[*]."email"'))::text as email_fts,
    (jsonb_path_query_array(co.phone_jsonb, '$[*]."number"'))::text as phone_fts,
    c.name as company_name,
    count(distinct t.id) filter (where t.done_date is null) as nb_tasks
from public.contacts co
    left join public.tasks t on co.id = t.contact_id
    left join public.companies c on co.company_id = c.id
group by co.id, c.name;

create view public.activity_log as
select
    ('company.' || c.id || '.created') as id,
    'company.created' as type,
    c.created_at as date,
    c.id as company_id,
    c.sales_id,
    c.organization_id,
    to_json(c.*) as company,
    null::json as contact,
    null::json as deal,
    null::json as contact_note,
    null::json as deal_note
from public.companies c
union all
select
    ('contact.' || co.id || '.created') as id,
    'contact.created' as type,
    co.first_seen as date,
    co.company_id,
    co.sales_id,
    co.organization_id,
    null::json as company,
    to_json(co.*) as contact,
    null::json as deal,
    null::json as contact_note,
    null::json as deal_note
from public.contacts co
union all
select
    ('contactNote.' || cn.id || '.created') as id,
    'contactNote.created' as type,
    cn.date,
    co.company_id,
    cn.sales_id,
    cn.organization_id,
    null::json as company,
    null::json as contact,
    null::json as deal,
    to_json(cn.*) as contact_note,
    null::json as deal_note
from public.contact_notes cn
    left join public.contacts co on co.id = cn.contact_id
union all
select
    ('deal.' || d.id || '.created') as id,
    'deal.created' as type,
    d.created_at as date,
    d.company_id,
    d.sales_id,
    d.organization_id,
    null::json as company,
    null::json as contact,
    to_json(d.*) as deal,
    null::json as contact_note,
    null::json as deal_note
from public.deals d
union all
select
    ('dealNote.' || dn.id || '.created') as id,
    'dealNote.created' as type,
    dn.date,
    d.company_id,
    dn.sales_id,
    dn.organization_id,
    null::json as company,
    null::json as contact,
    null::json as deal,
    null::json as contact_note,
    to_json(dn.*) as deal_note
from public.deal_notes dn
    left join public.deals d on d.id = dn.deal_id;
